import { createReadStream } from 'node:fs';
import { mkdir, rename, rm, stat, writeFile } from 'node:fs/promises';
import { createCipheriv, createDecipheriv, randomBytes, randomUUID } from 'node:crypto';
import path from 'node:path';
import type { Readable } from 'node:stream';

/**
 * File storage (doc 03 §8, doc 07 §2).
 *
 * An interface with one implementation, so object storage can replace the disk
 * later without a schema change or a route change. Everything above this file
 * knows about a relative path and a data key, and nothing else.
 *
 * Two layers of encryption, on purpose. The volume is encrypted at rest, which
 * protects a stolen disk. Each file is then encrypted again under its own
 * random data key, which is stored wrapped by the master key, so a backup or a
 * volume snapshot without the key ring is noise.
 *
 * On-disk layout, all one file:
 *
 *   nonce (12) | tag (16) | ciphertext
 *
 * The tag sits in the header rather than at the end so a download can set it
 * before streaming, which is what makes the read a stream rather than a 20 MB
 * buffer held in memory per request.
 */

const NONCE_BYTES = 12;
const TAG_BYTES = 16;
const HEADER_BYTES = NONCE_BYTES + TAG_BYTES;

export class StorageError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'StorageError';
  }
}

export type StoredFile = {
  /** Relative to the storage root, so the root can move. */
  path: string;
  /** The per-file data key. The caller wraps it with the master key. */
  key: Buffer;
  byteSize: number;
};

export interface FileStore {
  put(plaintext: Buffer, extension: string): Promise<StoredFile>;
  /** Writes under a known key, for a thumbnail that shares its file's key. */
  putWith(plaintext: Buffer, key: Buffer, extension: string): Promise<StoredFile>;
  read(relativePath: string, key: Buffer): Promise<Buffer>;
  stream(relativePath: string, key: Buffer): Promise<Readable>;
  remove(relativePath: string): Promise<void>;
  exists(relativePath: string): Promise<boolean>;
  /** Proves at boot that files can actually be written. */
  ensureWritable(): Promise<void>;
}

/**
 * Two levels of hashed directory, so a folder never holds a million files. The
 * name is random rather than derived from the id, because a storage path that
 * can be guessed from an id is one misconfigured nginx away from being served
 * directly.
 */
function newRelativePath(extension: string): string {
  const name = randomUUID().replace(/-/g, '');
  return path.join(name.slice(0, 2), name.slice(2, 4), `${name}.${extension}enc`);
}

export function newDataKey(): Buffer {
  return randomBytes(32);
}

export class LocalFileStore implements FileStore {
  constructor(private readonly root: string) {}

  /**
   * Refuses to look outside the root.
   *
   * The paths handled here are generated by this file, never supplied by a
   * caller, so this should be unreachable. It is here because "should be
   * unreachable" is how directory traversal gets shipped.
   */
  private absolute(relativePath: string): string {
    const resolved = path.resolve(this.root, relativePath);
    const root = path.resolve(this.root);
    if (resolved !== root && !resolved.startsWith(root + path.sep)) {
      throw new StorageError('That storage path is outside the attachment volume');
    }
    return resolved;
  }

  async put(plaintext: Buffer, extension: string): Promise<StoredFile> {
    return this.putWith(plaintext, newDataKey(), extension);
  }

  async putWith(plaintext: Buffer, key: Buffer, extension: string): Promise<StoredFile> {
    const relativePath = newRelativePath(extension);
    const absolute = this.absolute(relativePath);
    await mkdir(path.dirname(absolute), { recursive: true });

    const nonce = randomBytes(NONCE_BYTES);
    const cipher = createCipheriv('aes-256-gcm', key, nonce);
    const ciphertext = Buffer.concat([cipher.update(plaintext), cipher.final()]);
    const body = Buffer.concat([nonce, cipher.getAuthTag(), ciphertext]);

    // Written beside and renamed, so a crash mid-write cannot leave a
    // half-file that reads as corruption rather than as absence.
    const temporary = `${absolute}.${randomUUID().slice(0, 8)}.part`;
    await writeFile(temporary, body, { mode: 0o600 });
    await rename(temporary, absolute);

    return { path: relativePath, key, byteSize: plaintext.byteLength };
  }

  async read(relativePath: string, key: Buffer): Promise<Buffer> {
    const chunks: Buffer[] = [];
    const source = await this.stream(relativePath, key);
    for await (const chunk of source) chunks.push(chunk as Buffer);
    return Buffer.concat(chunks);
  }

  /**
   * The download path. Reads the header, then hands back the decrypting side
   * of the pipe so a 20 MB file is never held whole in memory per request.
   *
   * A tampered or truncated file fails on the authentication tag at the very
   * end, after some plaintext has already been written to the response. That
   * is inherent to streaming AES-GCM: the alternative is buffering the whole
   * file to verify first, which is the cost this exists to avoid. The response
   * is destroyed rather than completed, so the client sees a broken transfer
   * rather than a short file it believes.
   */
  async stream(relativePath: string, key: Buffer): Promise<Readable> {
    const absolute = this.absolute(relativePath);

    const header = await readHeader(absolute);
    const decipher = createDecipheriv('aes-256-gcm', key, header.nonce);
    decipher.setAuthTag(header.tag);

    const body = createReadStream(absolute, { start: HEADER_BYTES });
    body.on('error', (error) => decipher.destroy(error));

    return body.pipe(decipher);
  }

  async remove(relativePath: string): Promise<void> {
    await rm(this.absolute(relativePath), { force: true });
  }

  async exists(relativePath: string): Promise<boolean> {
    try {
      await stat(this.absolute(relativePath));
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Creates the volume and writes a probe file to it.
   *
   * A container running as an unprivileged user against a root-owned mount can
   * do everything except write, which otherwise shows up as a 500 the first
   * time a worker in a house tries to attach a photo. Finding that at boot,
   * with the path in the message, is worth the two syscalls.
   */
  async ensureWritable(): Promise<void> {
    const root = path.resolve(this.root);
    const probe = path.join(root, '.writable');
    try {
      await mkdir(root, { recursive: true });
      await writeFile(probe, '', { mode: 0o600 });
      await rm(probe, { force: true });
    } catch {
      throw new StorageError(
        `The attachment volume at ${root} is not writable. ` +
          'Check ATTACHMENT_DIR and the ownership of the mount.',
      );
    }
  }
}

async function readHeader(absolute: string): Promise<{ nonce: Buffer; tag: Buffer }> {
  const chunks: Buffer[] = [];
  const source = createReadStream(absolute, { start: 0, end: HEADER_BYTES - 1 });
  for await (const chunk of source) chunks.push(chunk as Buffer);
  const header = Buffer.concat(chunks);
  if (header.length < HEADER_BYTES) {
    throw new StorageError('That stored file is too short to be valid');
  }
  return {
    nonce: header.subarray(0, NONCE_BYTES),
    tag: header.subarray(NONCE_BYTES, HEADER_BYTES),
  };
}

export function createFileStore(root: string): FileStore {
  return new LocalFileStore(root);
}
